[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
hook_add = '''
let g:highlightedyank_highlight_duration = 150
'''
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
hook_add = '''
	map <Leader><Leader>f <Plug>(easymotion-bd-f)
	nmap <Leader><Leader>f <Plug>(easymotion-overwin-f)
	map <Leader><Leader>t <Plug>(easymotion-bd-t)
	nmap <Leader><Leader>t <Plug>(easymotion-overwin-t)
	map <Leader><Leader>s <Plug>(easymotion-bd-f2)
	nmap <Leader><Leader>s <Plug>(easymotion-overwin-f2)
	map <Leader><Leader>/ <Plug>(easymotion-sn)
	omap <Leader><Leader>/ <Plug>(easymotion-tn)
	map <Leader><Leader>h <Plug>(easymotion-linebackward)
	map <Leader><Leader>l <Plug>(easymotion-lineforward)
	map <Leader><Leader>j <Plug>(easymotion-j)
map <Leader><Leader>k <Plug>(easymotion-k)
	let g:EasyMotion_smartcase = 1
	'''
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
hook_add = '''
	nmap s <Plug>Sneak_s
	nmap S <Plug>Sneak_S
	'''
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
