-- vim.cmd[[autocmd ColorScheme * hi CursorLine ctermfg=15 ctermbg=242 guibg=#161F25]]
-- vim.cmd[[autocmd ColorScheme * hi LspDiagnosticsDefaultError guifg=#738C9C]]
vim.cmd[[autocmd ColorScheme * hi TabLineSel guibg=#b8860b guifg=black]]
vim.cmd[[set termguicolors]]
vim.cmd[[colorscheme codedark]]
